language: python

env:
  global:
    - PYENV_ROOT="$HOME/.pyenv"
    - PYENV="$PYENV_ROOT/bin/pyenv"

matrix:
  include:
    - python: "2.7"
      env:
        - PYENV_PYTHON_VER=2.7.11
    - python: "3.4"
      env:
        - PYENV_PYTHON_VER=3.4.4
        - BIDICT_COVERAGE_DISABLE=1
    - python: "3.5"
      env:
        - PYENV_PYTHON_VER=3.5.1
    - python: "pypy"
      env:
        - PYENV_PYTHON_VER=pypy-4.0.1
        - BIDICT_COVERAGE_DISABLE=1

install:
  # based on https://github.com/frol/flask-restplus-server-example/blob/018f48e5/.travis.yml
  - |
      if [ -f "$PYENV" ]; then
        pushd "$PYENV_ROOT" && git pull && popd
      else
        rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
      fi
      "$PYENV" install --skip-existing "$PYENV_PYTHON_VER"
      export PYTHON="$PYENV_ROOT/versions/$PYENV_PYTHON_VER/bin/python"
      export VENV="$HOME/virtualenvs/$PYENV_PYTHON_VER"
      virtualenv --python="$PYTHON" "$VENV"
      source "$VENV/bin/activate"
  - travis_retry pip install -e .[test]
  - test -n "$BIDICT_COVERAGE_DISABLE" && travis_retry pip install coveralls || echo "Skipping coveralls"

script:
  - ./test.sh

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.hypothesis
    - $PYENV_ROOT

after_success:
  - test -n "$BIDICT_COVERAGE_DISABLE" && echo "Running coveralls" && coveralls

sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bf64fb45a633c0935b9b

deploy:
  provider: pypi
  user: jab
  password:
    secure: B9LLgXkTbtjeC/IbH4wh9PEBzvKEAuYo3EBNW5f1xuLqVqtsysIyxJa5ar/FQ4qwUCBwZPFAXFurN3lLzRhb2Tc04YQ0GYVv6f8lkzwrjoWau4iB9Qt/nnvdRa7KryEJvtenHCAnwoEUaADCjkZjwo6fIA0hEOLB6/AYfhfgXYA=
  on:
    tags: true
    branch: master
